apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicwriter-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: basicwriter-deployment
  template:
    metadata:
      labels:
        app: basicwriter-deployment
    spec:
      containers:
      - name: basicwriter-deployment
        image: ormicodemo.azurecr.io/akskedademo.basicwriterworker:1.0.0.3
        env:
        - name: queueName
          value: q1
        - name: ConnectionStrings__serviceBus
          valueFrom:
            secretKeyRef:
             name: servicebus-secret
             key: servicebus-connectionstring
