apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: basicreader-scaler
#  labels:
#    app: order-processor
#    name: order-processor
spec:
  scaleTargetRef:
    name: basicreader-deployment #order-processor
  # minReplicaCount: 0 Change to define how many minimum replicas you want
  maxReplicaCount: 10
  cooldownPeriod:  30
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: q1
      #queueLength: '1' #'5'
    authenticationRef:
      name: trigger-auth-service-bus-basicreader