apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-service-bus-basicreader
spec:
  secretTargetRef:
  - parameter: connection
    name: servicebus-secret
    key: servicebus-management-connectionstring
